spring:
  data:
    mongodb:
      uri: mongodb+srv://ilijakrilovic:SgjIwqkZMqsDty39@cluster0.tzzvh1b.mongodb.net/?retryWrites=true&w=majority
      database: applaudify
server:
  address: 0.0.0.0
  port: 8080
