name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build JAR file
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t applaudify .
        
      - name: Deploy to Fly.io
        run: flyctl deploy --image applaudify

        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
